urly_app/urls.py
from django.conf.urls import patterns, include, url
 
urlpatterns = patterns('urly_app.views',
    url(r'^;', 'triage'),

    url(r'^$', 'redirect_to_home'),
    # url(r'^$', 'shorten'),

    url(r'\w{1,18}-$', 'is_short_taken'),

                       # url(r'^shorten/?(?P<short_code_requested>[^/]+)/?(?P<long_url_specified>(https?|mailto|tel|data):.*)$', 'shorten', name='shorten'),
    url(r'^shorten/?(?P<long_url_specified>.*)$', 'shorten', name='shorten'),
    url(r'^qr(?P<pixels_square>[0-9]+)(?P<format_extension>[a-z]+)/?(?P<data_to_encode>.*)$', 'qr_code'),

                       # redirect short to long, for any short base with no path suffix, e.g. go.spe.org/atce
#    url(r'^(?P<short_code>\w{1,18})$', 'redirect', name='redir'),

    #    url(r'^send_link_info/(?P<recipients>[^/]+)/(?P<short_base>.+/)(?P<short_code>\w{4,30})$', 'get_link_info'),
    # url(r'^(?P<short_base_path>.+/)(?P<short_code>\w{1,18})(?P<recipients>\+)$', 'get_link_info'),
    # url(r'\+$', 'get_link_info'),
    # url(r'^(?P<short_base_path>.+/)(?P<short_code>\w{1,18})\+$', 'get_link_info'),
    # url(r'^(.+/)?(?P<short_code>\w{1,18})\+$', 'test'),
    # url(r'^(?P<short_base_path>.+/)(?P<short_code>\w{1,18})(?P<recipients>[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z]+|\+)$', 'get_link_info'),
    #    url(r'^send_link_info/(?P<recipients>[^/]+)/(?P<short_url>(https?://.+/\w{4,30})$)', 'send_link_info'),

    # url(r'^send_link_info/(?P<recipients>[^/]+)/(?P<short_code>\w{1,18})$', 'get_link_info'),
    url(r'^(send_link_info/)?(?P<short_code>\w{1,18})/(?P<recipients>[^/]*)$', 'get_link_info'),
    # url(r'^(?P<short_code>\w{1,18})/(?P<recipients>[^/]+)$', 'get_link_info'),

                       #    url(r'^link/(?P<short_base>[^/]+/)(?P<short_url>\w{4,30})$', 'show_link_info'),
#    url(r'^(?P<short_code>\w{4,30})\+$', 'preview', name='preview'),
#    url(r'^(?P<short_code>\w{4,30}):$', 'edit', name='edit'),

    # redirect short to long, for any short base with a path suffix, e.g. www.spe.org/go/atce
    # url(r'^(?P<short_base_path>.+/)(?P<short_code>\w{1,18})$', 'redirect', name='redir'),

    url(r'.', 'triage'),

    )

urly_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
 
urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('urly_app.urls', namespace='urly_app')),
    )

urly_app/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
import random, string, json, re, requests, datetime
from urly_app.models import Link
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.core.context_processors import csrf
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt


@csrf_exempt
def redirect_to_home():
    return HttpResponseRedirect('http://www.spe.org/')


@csrf_exempt
def redirect_to_home():
    return HttpResponseRedirect('http://www.spe.org/')


def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('urly_app/index.htm', c)


def multi_match(dic):
    pattern = '^(' + '|'.join(map(re.escape, dic.keys())) + ')'
    return re.search(pattern, lambda m: dic[m.group()])


def multi_replace(dic, txt):
    pattern = '^(' + '|'.join(map(re.escape, dic.keys())) + ')'
    return re.sub(pattern, lambda m: dic[m.group()], txt)


@csrf_exempt
def qr_code(request, data_to_encode='https://v.gd/winlaw', pixels_square='720', format_extension='png', ecc='L'):
    if len(str(data_to_encode)) < 1:
        return None
    api_base = 'http://api.qrserver.com/v1/create-qr-code/'
    referrer = 'http://goqr.me/'
    px = int(pixels_square)  # can range from 150 to 1000
    p = {}
    p['color'] = '223344'  # typical webby RGB in hex
    p['bgcolor'] = 'FBFBFB'  # typical webby RGB in hex
    p['data'] = unicode(data_to_encode)  # or 'https%3A%2F%2Fv.gd%2Fwinlaw'
    p['qzone'] = 1
    p['margin'] = 0
    p['size'] = str(px) + 'x' + str(px)
    p['ecc'] = str(ecc).upper()  # L (Low) is recommended; can be L, M, Q, H
    p['format'] = str(format_extension).lower()  # png is recommended; can be svg, eps, png, jpg
    h = {'Referer': referrer}  # this might not be required anymore
    req = requests.get(api_base, headers=h, params=p)
    res = HttpResponse(req.content)
    res['Content-Type'] = 'image/' + p['format']
    return res


@csrf_exempt
def proxy_get_status_code(from_url, to_url):
    h = {'Referer': from_url}
    r = requests.get(to_url, headers=h, params=t)
    return r.status_code


@csrf_exempt
def triage(request):
    # first we need to combine the requested URI with the HTTP Host header
    # in order to figure out the intended action and be able to do a DB lookup
    u = request.scheme + '://' + request.get_host() + request.get_full_path()

    if re.match('~$', u):
        return HttpResponse(intent + ': @TODO parse out recipient(s)<br />"' + t + '"<br />and then pipe them to the get_link_info() function.  u=<br />"' + u + '"')

    # define how we pluck usernames/mailboxes out of the URL, for when staff wants to get info about a short URL
    email_recipients_regex = r'((,[A-Za-z0-9_-]{1,36}@(spe\.org)?)+)$'  # max 36 chars per mailbox name; all goes in backreference #1

    # define how we grab the right pieces of a URL and use them for real-time QR code generation
    qr_code_images_regex = r'(_([0-9]+)x[0-9]*([LMQH]|\B)\.(png|svg|jpg|eps))$'  # standard image URL suffix; all goes in backreference #1, pixels_square in #2, ECC level in #3, format_extension in #4

    # define what "special" characters we allow for indicating intent
    suffixes_regex = '([:+~\.]|@(spe\.org)?)$'

    if '/' in request.get_full_path():
        p = request.get_full_path()
        short_code_pos = p.rfind('/') + 1
        short_base_choices = re.sub("\('|','[^']+'\)", '', '|'.join(map(re.escape, dict(Link.BASE_CHOICES).keys())))
        # short_base_choices_regex = '^(' + '|'.join(map(str, Link.BASE_CHOICES)) + ')'
        short_base_choices_regex = '^(' + short_base_choices + ')'
        short_base_choices_match = str(re.search(short_base_choices_regex, u).group(0))
        short_base = str(short_base_choices_match)
        # short_base = request.scheme + '://' + request.get_host() + '/' + re.sub(suffixes_regex, '', p[1:short_code_pos])

        # check to see whether or not the request included a verb -- any path portion besides [BASE + CODE]
        after_base = re.sub(suffixes_regex, '', u.replace(short_base, ''))
        if '/' in after_base:
            verb_with_trailing_slash = after_base.split('/')[0] + '/'
            short_code = after_base.split('/')[1]
        else:
            verb_with_trailing_slash = ''
            short_code = re.sub(qr_code_images_regex, '', re.sub(suffixes_regex, '', u.replace(short_base, '')))
        intent_suffix = u.replace(short_base + verb_with_trailing_slash + short_code, '')

    # l = get_object_or_404(Link, short_base=short_base, short_code=short_code)
    try:
        l = Link.objects.get(short_base=short_base, short_code=short_code)
        m = 'Match'
        tu = l.redirect_target_url()
        tt = l.tracking_type
        ttd = l.get_tracking_type_display()
    except Link.DoesNotExist:
        m = 'No matches'
        tu = ''
        tt = ''
    v = verb_with_trailing_slash.replace('/','')
    # intent = 'shorten' if v =='s' else 'redirect' if v =='r' else 'preview' if intent_suffix =='+' else 'check_if_taken' if intent_suffix =='?' else 'admin' if intent_suffix ==':' else 'home' if v=='' and short_code =='' and intent_suffix =='' else 'redirect'
    # so far, this is the closest thing I can find to mimic the simple standard switch/case construct which python lacks
    intent = 'email_link_info' if re.match(email_recipients_regex, p) \
        else 'preview' if intent_suffix == '+' \
        else 'check_if_taken' if intent_suffix == '~' \
        else 'qr_code' if re.match(qr_code_images_regex, after_base.replace(short_code, '')) \
        else 'admin' if intent_suffix == ':' \
        else 'home' if v == '' and short_code == '' and intent_suffix == '' \
        else 'redirect'
    # OK, at this point, we should know the intent and have all the pieces in place to act on it

    if intent == 'check_if_taken':
        return is_short_taken(request, short_base, short_code)

    if intent == 'preview':
        t = l.tracking_string
        tu = l.redirect_target_url()
        l.hit_count += 1
        l.save()

        if tt == 's': # the tracking hit needs to be fired server-side
            t = l.tracking_string
            tu = l.canonical_url
            h = {'Referer': u}
            r = requests.get(tu, headers=h, params=t)
            try:
                rsc = r.status_code
            except:
                rsc = 0
        else: # no need for the server to do anything; either there is no tracking or else the client will do it
            rsc = 0

        c = {} # context object that will be passed to the template
        c['destination_url'] = tu
        c['tracking_type_display'] = str(ttd).lower()
        c['tracking_string'] = t
        c['tracking_hit_status_code'] = rsc
        c['resource_title'] = tu
        c['delay_seconds'] = 7
        return render_to_response('urly_app/interstitial.htm', c)

    if intent == 'qr_code':
        data_to_encode = short_base + short_code
        pixels_square = re.sub(qr_code_images_regex, r'\2', after_base.replace(short_code, ''))
        ecc = '' + re.sub(qr_code_images_regex, r'\3', after_base.replace(short_code, ''))
        format_extension = re.sub(qr_code_images_regex, r'\4', after_base.replace(short_code, ''))
        return qr_code(request, data_to_encode=data_to_encode, pixels_square=pixels_square, format_extension=format_extension, ecc=ecc)

    if intent == 'admin':
        return HttpResponseRedirect('http://go.spe.org/admin/urly_app/link/' + l.short_url_hash + '/')

    if intent == 'redirect':
        # identify whether the short base being used is one that integrates with EVA for event code to be short code
#        domain = re.sub('(^https?://|(:[0-9]+)?/(go/)?$)', '', short_base)
        if short_base == 'http://go.spe.org/' or short_base == 'http://2s.pe/' or short_base == 'http://4s.pe/':
#        if True:

            # identify event codes; use the detail site URL we already have in EVA
            event_code_regex1 = '^(20)?(([0-9]{2})[A-Za-z0-9]{2,4})$' # for easier readability, these two are not combined
            event_code_regex2 = '^([A-Za-z]{2,4})(20)?([0-9]{2})$' # this one catches a few forum edge-case stragglers
            eva_redir_prefix = 'http://eva.spe.org/events/jump/'
            eva_redir_suffix = '?via=' + short_base + short_code

            if re.match(event_code_regex1, short_code) or re.match(event_code_regex2, short_code):
                return HttpResponseRedirect(eva_redir_prefix + short_code + eva_redir_suffix)

        if tt == 'c':
            l.hit_count += 1
            l.save()
            return HttpResponseRedirect(str(l.redirect_target_url()))

        if tt == 's':
            t = l.tracking_string
            u = l.canonical_url
            l.hit_count += 1
            l.save()
            return HttpResponse(intent + ': @TODO conditionally trigger a server-side tracking hit on<br />"' + t + '"<br />and then redirect you to:<br />"' + u + '"')

        if tt == 'n':
            l.hit_count += 1
            l.save()
            return HttpResponseRedirect(str(l.canonical_url))

    if intent == 'email_link_info':
        return HttpResponse(
            intent + ': @TODO parse out recipient(s)<br />"' + t + '"<br />and then pipe them to the get_link_info() function:<br />"' + re.sub(email_recipients_regex, '\1', p) + '"')
        return get_link_info(request,short_code,recipients)

urly_app/templates/urly_app/base.html
<!DOCTYPE html><html><head>
 <title>{% block title %}URL Shortener{% endblock %}</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'urly_app/css/custom.css' %}" />
 <script src="//code.jquery.com/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div id="wrap">
<header>{% block body_header %}<h1><span data-href="{% url 'urly_app:home' %}">URL Shortener</span></h1>
{% endblock %}</header>
  
<div id="content">
{% block content %}
  
{% endblock %}
</div>
</div>


</body></html>

urly_app/templates/urly_app/index.htm
{% extends "urly_app/base.html" %}

{% block title %}URL Shortener{% endblock %}

{% block body_header %}<h1><a href="{% url 'urly_app:shorten' %}">URLy</a> <small>&mdash; shorten any URL &mdash; and optionally track its use</small></h1>{% endblock %}
  
{% block content %}{% endblock %}

urly_app/templates/urly_app/interstitial.htm
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Refresh" content="{{ delay_seconds|add:"1" }}; URL={{ destination_url }}" />

    <title>{{ resource_title }}</title>

	<style type="text/css">
	html {
		background: #eee;
	}
	a {
		color: #57b;
	}
	.iyf_box {
		background: #fff;
        margin: 0.9em;
        padding: 0.9em;
{#		margin: 18px auto;#}
{#		width: 720px;#}
{#		padding: 36px;#}
		text-align: center;
		font-family: Georgia, "Times New Roman", Times, serif;
		color: #555;
		-moz-border-radius: 18px;
		-khtml-border-radius: 18px;
		-webkit-border-radius: 18px;
		border-radius: 18px;
	}
	h1 {
		font-size: 2.7em;
		font-weight: normal;
		color: #999;
	}
	h2 {
		font-size: 1.8em;
		font-weight: normal;
	}
	</style>
  </head>
  <body>
	<div class="iyf_box">
		<h1>{{ resource_title }}</h1>

{% if tracking_hit_status_code %}
        <p>(Server-side tracking was triggered, and the response status code was <b>{{ tracking_hit_status_code }}</b>.</p>
{% else %}
        <!-- This particular link is configured for "{{ tracking_type_display }}" so the server did not trigger any tracking request -->
{% endif %}

		<h2>You are now being directed to the requested resource...</h2>

		<p>(Please <a href="{{ destination_url }}">&raquo; click here</a> if it takes more than {{ delay_seconds|add:"3" }} seconds.)</p>

        <hr />

		<p align="right"><small><a href="/shorten">URLy</a></small></p>

	</div>
	<script>
		setTimeout(function(){
			window.location.href='{{ destination_url }}';
		},(1000 * {{ delay_seconds }} + 1));
	</script>
	</body>
</html>

urly_app/templates/urly_app/redirect.htm
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Refresh" content="{{ delay_seconds|add:"1" }}; URL={{ destination_url }}" />

    <title>{{ resource_title }}</title>

	<style type="text/css">
	html {
		background: #eee;
	}
	a {
		color: #57b;
	}
	.iyf_box {
		background: #fff;
		margin: 18px auto;
		width: 720px;
		padding: 36px;
		text-align: center;
		font-family: Georgia, "Times New Roman", Times, serif;
		color: #555;
		-moz-border-radius: 18px;
		-khtml-border-radius: 18px;
		-webkit-border-radius: 18px;
		border-radius: 18px;
	}
	h1 {
		font-size: 2.7em;
		font-weight: normal;
		color: #999;
	}
	h2 {
		font-size: 1.8em;
		font-weight: normal;
	}
	</style>
  </head>
  <body>
	<div class="iyf_box">
		<h1>{{ resource_title }}</h1>

		<h2>You are now being directed to the requested resource...</h2>

		<p>(Please <a href="{{ destination_url }}">&raquo; click here</a> if it takes more than {{ delay_seconds|add:"3" }} seconds.)</p>

        <hr />

		<p align="right"><small><a href="{% url 'urly_app:home' %}">URLy</a></small></p>

	</div>
	<script>
		setTimeout(function(){
			window.location.href='{{ destination_url }}';
		},(1000 * {{ delay_seconds }} + 1));
	</script>
	</body>
</html>